### ISSUE TITLE
No pypi package

### ISSUE THREAD

**Issue by ZeeD** [mastak/airflow_multi_dagrun#10]
Hi.
I think your project it's useful and I would like to integrate your operators in my project.

Do you have some plans to distribute the package via pypi?

**Comment by mastak** [comment]
Hi @ZeeD,

The main reason why I didn't create a python package and put it to pypi - it does not help. Python packages install into python lib path (example `...lib/python/site-packages/...`) but airflow plugin should be copied into `$AIRFLOW_HOME/plugins` (https://airflow.apache.org/docs/stable/plugins.html).

**Comment by ZeeD** [comment]
Hi @mastak 
I asked because it would make easier for me to use the code (with autocomplete and stuff) inside my IDE without dealing with PYTHONPATH and other variables.
moreover I see on https://airflow.apache.org/docs/stable/plugins.html#plugins-as-python-packages that it's possible to use install without the `$AIRFLOW_HOME/plugin` trick

**Comment by mastak** [comment]
Agree. I will try to do it in the next few days.

**Comment by mastak** [comment]
@ZeeD  you can try https://pypi.org/project/airflow-multi-dagrun/

If you will have some issue - feel free to write.

**Comment by ZeeD** [comment]
I just recreated my virtualenv with your packaged plugin. Everything seems to work as intented!
