### ISSUE TITLE
start_date: datetime.utcnow() causes DAG to run but trigger no tasks

### ISSUE THREAD

**Issue by inventionlabsSydney** [mastak/airflow_multi_dagrun#13]
Airflow Version: 1.10.9

When setting the child DAG as per your example with default options: 
```
dag = DAG(
   dag_id='example_target_dag',
   schedule_interval=None,
   default_args={'start_date': datetime.utcnow(), 'owner': 'airflow'},
)


def run_this_func(dag_run, **kwargs):
   print("Chunk received: {}".format(dag_run.conf['index']))


chunk_handler = PythonOperator(
   task_id='chunk_handler',
   provide_context=True,
   python_callable=run_this_func,
   dag=dag
)
```

Where start_date `{'start_date': datetime.utcnow()}` causes the Dag to execute but all tasks are skipped (including the initial task)
Changing this to `days_ago(0)` resolves it.

Thanks,
Karl.

**Comment by mastak** [comment]
Hi @inventionlabsSydney 

yes `start_date` can be a fixed date from the past, or can be `days_ago(1)`
sorry for the late response.
