### ISSUE TITLE
allow custom run_id

### ISSUE THREAD

**Issue by waleedsamy** [mastak/airflow_multi_dagrun#18]
With https://github.com/apache/airflow/pull/6317, TriggerDagRunOperator changed to drop the use of DagRunOrder and you thankfully adapted their way. However [I think we are following bad decision](https://github.com/apache/airflow/pull/6317#issuecomment-829364149) by allowing TriggerMultiDagRunOperator to use [unidentifiable run_id](https://github.com/mastak/airflow_multi_dagrun/blob/428085742cd4154a4aba957f6ddf6555701e7719/airflow_multi_dagrun/operators.py#L36)

I'd like to discuss the possibility of restoring the old behavior where TriggerMultiDagRunOperator#python_callable can return DagRunOrder, so a user can provide custom+dynamic run_id.

In my case, I use TriggerMultiDagRunOperator to trigger thousands of dagruns and I assign for every one of those an identifiable run_id that can distinguish every dagrun from the other. surrendering indefinable run_id with gabbrish one is not wise at all.
WDYT?

**Comment by waleedsamy** [comment]
Created an airflow issue https://github.com/apache/airflow/issues/17438

**Comment by mastak** [comment]
Hi @waleedsamy 
Added it in the new version 2.2.0. Here you can find an example:
https://github.com/mastak/airflow_multi_dagrun/blob/v2.2.0/examples/trigger_with_custom_trigger_id.py#L12

Be careful, `run_id` has to be unique.
