### ISSUE TITLE
Auto-apply ``apply_default`` decorator

### ISSUE THREAD

**Issue by rtritto** [mastak/airflow_multi_dagrun#19]
From `airflow` [2.1.0rc2](https://github.com/apache/airflow/releases/tag/2.1.0rc2), has been added an improvement:
- Auto-apply ``apply_default`` to subclasses of ``BaseOperator``

During `airflow db upgrade` command, I get different warnings as deprecation.

Simply remove the import of ``apply_defaults`` decorator and ``@apply_default``.

**Comment by mastak** [comment]
done
