### ISSUE TITLE
Create a bridge release tha allow airflow v1.10.14 to use same approach as airflow v2.*

### ISSUE THREAD

**Issue by honarkhah** [mastak/airflow_multi_dagrun#21]
Goal:

Bridge release can help people to upgrade their dags before upgrading the entire airflow and test out everything

**Comment by mastak** [comment]
hi @honarkhah 
It sounds interesting, can you create a PR with the required changes?
I don't have enough time now to do it myself, but I can review your solution or answer your questions.
