### ISSUE TITLE
Adding wait_for_completion = True feature of TriggerDagRunOperator

### ISSUE THREAD

**Issue by VaibhavSingh98** [mastak/airflow_multi_dagrun#26]
Hi,

Is it possible to add `wait_for_completion = True` feature in this so that my controller dag waits for target dag execution completion and then proceeds with the next step?

**Comment by mastak** [comment]
Hi @VaibhavSingh98 
there is a `MultiDagRunSensor` for such a purpose

https://github.com/mastak/airflow_multi_dagrun/blob/master/examples/trigger_with_multi_dagrun_sensor.py#L37
