### ISSUE TITLE
handle DagRunAlreadyExists

### ISSUE THREAD

**Issue by waleedsamy** [mastak/airflow_multi_dagrun#27]
If TriggerMultiDagRunOperator failed and set to be rescheduled, It may have some dagruns that already created in the first run.... We need to ignore DagRunAlreadyExists but collect the dag_run.id to be stored in TriggerMultiDagRunOperator#CREATED_DAGRUN_KEY.

**Comment by mastak** [comment]
Hi @waleedsamy 
It sounds not clear to me, can you provide more details?

**Comment by waleedsamy** [comment]
In case of [run_id](https://github.com/mastak/airflow_multi_dagrun/blob/3998b26bbacabe1be4ee85c8c35a9d189f3a6e31/airflow_multi_dagrun/operators.py#L34) is provided by the caller of TriggerMultiDagRunOperator.. It may happen that there is an issue while TriggerMultiDagRunOperator did not finish successfully, maybe it get killed externally while it is half way creating dagruns. So, we come to state where some dagruns already created but some did not and Airflow will put back the task to reschedule state... In the second run [trigger_dag](https://github.com/mastak/airflow_multi_dagrun/blob/3998b26bbacabe1be4ee85c8c35a9d189f3a6e31/airflow_multi_dagrun/operators.py#L38) will fail with DagRunAlreadyExists for the ones the created in the first execution of TriggerMultiDagRunOperator...

In general, I believe we need to handle the case where TriggerMultiDagRunOperator fails while creating dagruns to avoid duplicate dagruns get created (they may have [different run_ids](https://github.com/mastak/airflow_multi_dagrun/blob/3998b26bbacabe1be4ee85c8c35a9d189f3a6e31/airflow_multi_dagrun/operators.py#L36) but the actual dag may get triggered multiple times with the same payload/conf).

I think providing [run_id](https://github.com/mastak/airflow_multi_dagrun/blob/3998b26bbacabe1be4ee85c8c35a9d189f3a6e31/airflow_multi_dagrun/operators.py#L34) by the user of TriggerMultiDagRunOperator made this case more obvious when duplicate dagruns get created.

**Comment by mastak** [comment]
created a fix, can you check with your case?
#30

**Comment by waleedsamy** [comment]
Looks good to me!
