### ISSUE TITLE
Also thanks / bigger changes

### ISSUE THREAD

**Issue by seeholza** [mastak/airflow_multi_dagrun#3]
Hi @mastak ,

Also big thanks from me! I was looking for a solution for this for a day and stumbled across your solution somehow by chance - google is not your friend in finding this.

I created a fork in https://github.com/flinz/airflow_multi_dagrun that does the following:
- include https://github.com/puckel/docker-airflow in the docker compose, remove most things from the Makefile (might be a bit too much)
- added travis CI
- patch multi_dagrun.py to work with airflow 1.10 and remove deprecation warnings (I opened a pull request with only this to you)

Please let me know if i should open a PR for the whole thing - I am not sure if the changes I added go beyond what you want to maintain here.

**Comment by mastak** [comment]
Hi @flinz ,

Thanks for your updates. 
I have merged it, hope you do not mind.

PS Some your commits didn't match to your profile, check your `~/.gitconfig`, email should be the same as in github.com

**Comment by seeholza** [comment]
Hi @mastak ,
No I absolutely don't mind, happy to have pointed it out. If you want some template as to adopting the travis CI configuration, check out https://github.com/flinz/airflow_multi_dagrun

Thanks also for the hint about the profile - I was on my second laptop that day.
