### ISSUE TITLE
Best way to use it?

### ISSUE THREAD

**Issue by theotheo** [mastak/airflow_multi_dagrun#8]
Hi there!

I'm curious about the best way to use your code. 
Just copy and paste? Or maybe it could be wrapped in a installable package?

**Comment by mastak** [comment]
Hi @theotheo!

It implemented as airflow plugin, so yes, you should copy `multi_dagrun` folder to your `$AIRFLOW_HOME/plugins` folder. It's a common way for airflow plugin:
https://airflow.apache.org/plugins.html
